// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dglkiwstjsssuwyfrsav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnbGtpd3N0anNzc3V3eWZyc2F2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTI0NjgsImV4cCI6MjA2NDAyODQ2OH0.Bn93yX0HbbCK_mBqDjV7DADWwFCcKfwE1KKEmifxNzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);